name: Checks that dependencies are up-to-date every month
on:
  schedule:
    - cron: "5 10 * * *"
    # - cron: "* * 1 * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run dependencies:check
      - run: echo "ğŸ This job's status is ${{ job.status }}."
